name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  tester-e-validacao:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar Código-fonte
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Instalar Dependências
        run: npm ci

      - name: Executar Linter
        run: npm run lint

      - name: Verificacao de seguranca de Dependencias (sast)
        run: npm audit --audit-level=high
